### ISSUE TITLE
Error introduced upgrading to bazel_rules_go

### ISSUE THREAD

**Issue by shaneikennedy** [mennanov/fieldmask-utils#17] opened 2021-05-28 13:59 UTC
```
com_github_mennanov_fieldmask_utils/copy.go:78:28: call of reflect.ValueOf copies lock value: google.golang.org/protobuf/types/known/anypb.Any contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex
```

Ref: https://stackoverflow.com/questions/64183794/why-do-the-go-generated-protobuf-files-contain-mutex-locks

Sorry I don't know what other sort of context you need here, I'm getting this error in a build for some other service at my org when updating another dependency that then requires me to update bazel_rules_go. It's a mess. 

If I can provide any more context please let me know. Although the error is happening because I'm upgrading some bazel package, the error looks to be a gRPC violation that became more strict in later versions.

**Comment by mennanov** [comment] 2021-05-28 23:49
I've found and fixed the issue. Please, try this branch https://github.com/mennanov/fieldmask-utils/tree/issue17_fix and let me know if it works for you. If it does i'll merge it to the main branch.

**Comment by mennanov** [comment] 2021-05-31 17:39
Closing the issue for now as the problem is resolved in the recent release https://github.com/mennanov/fieldmask-utils/releases/tag/v0.4.0

**Closed by mennanov** 2021-05-31 17:39 UTC
